name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent and add private key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Check SSH key
        run: ssh-add -l # This will list the added SSH keys for debugging

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2-IP> "mkdir -p /var/www/kraaiennest-api"
          scp -o StrictHostKeyChecking=no -r ./* ec2-user@<EC2-IP>:/var/www/kraaiennest-api/

      - name: Run deployment script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2-IP> "
          cd /var/www/kraaiennest-api &&
          sudo docker-compose down &&
          sudo docker-compose up --build -d"
