# Triggering build

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create directory on EC2 with correct ownership
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/kraaiennest-api && sudo chown -R ec2-user:ec2-user /var/www/kraaiennest-api"

      - name: Copy files to EC2 using rsync
        run: |
          rsync -avz --delete --exclude='node_modules' --exclude='.git' ./ ec2-user@${{ secrets.EC2_HOST }}:/var/www/kraaiennest-api/

      - name: Install dependencies and build TypeScript on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          cd /var/www/kraaiennest-api &&
          npm install &&
          npm run build  # Compile TypeScript files to JavaScript
          "

      - name: Restart application with PM2 (Run from dist with NODE_ENV=production)
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          cd /var/www/kraaiennest-api &&
          pm2 stop all || true &&  # Stops all running PM2 processes if any
          NODE_ENV=production pm2 start dist/index.js --name kraaiennest-api &&  # Set NODE_ENV to production
          pm2 save  # Saves the process list for PM2 to restart on reboot
          "
