name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest version of the checkout action

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0 # Updated to the latest version
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Use your GitHub secret for the EC2 SSH key

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/kraaiennest-api"
          scp -o StrictHostKeyChecking=no -r ./* ec2-user@${{ secrets.EC2_HOST }}:/var/www/kraaiennest-api/

      - name: Run deployment script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          cd /var/www/kraaiennest-api &&
          sudo docker-compose down &&
          sudo docker-compose up --build -d"
