# Trigger build
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create directory on EC2 with correct ownership
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/kraaiennest-api && sudo chown -R ec2-user:ec2-user /var/www/kraaiennest-api"

      - name: Copy files to EC2 using rsync
        run: |
          rsync -avz --delete --exclude='node_modules' --exclude='.git' ./ ec2-user@${{ secrets.EC2_HOST }}:/var/www/kraaiennest-api/

      - name: Install dependencies and build TypeScript on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          cd /var/www/kraaiennest-api &&
          npm install &&
          npm run build  # Compile TypeScript files to JavaScript
          "

      - name: Ensure only one instance is running with PM2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          cd /var/www/kraaiennest-api &&
          pm2 stop all || true &&
          pm2 delete all || true &&
          PORT=5000 ALLOWED_ORIGINS='${{ secrets.ALLOWED_ORIGINS }}' AUTH0_DOMAIN='${{ secrets.AUTH0_DOMAIN }}' AUTH0_AUDIENCE='${{ secrets.AUTH0_AUDIENCE }}' DB_HOST='${{ secrets.DB_HOST }}' DB_PORT='${{ secrets.DB_PORT }}' DB_NAME='${{ secrets.DB_NAME }}' DB_USER='${{ secrets.DB_USER }}' DB_PASSWORD='${{ secrets.DB_PASSWORD }}' API_KEY='${{ secrets.API_KEY }}' NODE_ENV=production pm2 start /var/www/kraaiennest-api/dist/index.js --name kraaiennest-api &&
          pm2 save
          "
