## Triggering a run on push to the main branch
name: Deploy to EC2

on:
  push:
    branches:
      - main # Specify the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3 # Use the latest available stable version
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/your/application  # Replace with the actual path on EC2
            git pull origin main
            npm install
            pm2 restart kraaiennest-api  # Ensure pm2 is set up and your app is named correctly
          EOF
