name: Test AWS IAM Role Setup

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::539247482630:role/access-test # Replace with your new role's ARN
          aws-region: eu-north-1
          audience: sts.amazonaws.com

      - name: Verify AWS Configuration
        run: aws sts get-caller-identity
